AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Step Function to automatically release created mac1/mac2 dedicated hosts after 24hrs (the minimum for Mac instances)

Resources:
  LogGroup: 
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      RetentionInDays: 14
  HostReleaseStepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/release-24h.asl.json
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt LogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeHosts
                - ec2:DescribeHostReservations
                - ec2:ReleaseHosts
              Resource: "*"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutLogEvents
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"
  StepFnTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: InvokeStepFn
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref HostReleaseStepFunction
  HostCreationEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - "aws.ec2"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventName:
            - AllocateHosts
          requestParameters:
            AllocateHostsRequest:
              InstanceType:
                - mac1.metal
                - mac2.metal
          responseElements:
            AllocateHostsResponse:
              hostIdSet:
                item:
                  - exists: true
      State: ENABLED
      Targets:
        - Arn: !Ref HostReleaseStepFunction
          Id: HostReleaseStepFunction
          RoleArn: !GetAtt StepFnTriggerRole.Arn
          InputTransformer:
            InputPathsMap:
              hosts: "$.detail.responseElements.AllocateHostsResponse.hostIdSet.item"
            InputTemplate: |
              {
                "targetHosts": [
                  <hosts>
                ]
              }

Outputs:
  HostReleaseStepFunctionArn:
    Description: "EC2 Mac host release Step Function ARN"
    Value: !Ref HostReleaseStepFunction
